stages:
  - build

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  tags:
    - linux-docker
  variables:
    __IMAGE_TAG: alpine-6.0-latest
  before_script:
    - 'docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}'
  script:
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:${__IMAGE_TAG}" .
    - |
      if [[ "${CI_COMMIT_BRANCH}" == "${CI_DEFAULT_BRANCH}" ]]
      then
        docker push "${CI_REGISTRY_IMAGE}:${__IMAGE_TAG}"
      fi
